In [251]:
# Libraries and dependencies
import numpy as np
import pandas as pd

In [252]:
# Read in the input files:
new_york_df = pd.read_csv('new_york_size.csv', skiprows=1)
bronx_df = pd.read_csv('bronx_size.csv', skiprows=1)
kings_df = pd.read_csv('kings_size.csv', skiprows=1)
queens_df = pd.read_csv('queens_size.csv', skiprows=1)
Richmond_df = pd.read_csv('Richmond_size.csv', skiprows=1)

In [253]:
# Change all the Id, i.e Id2 value, into integers:
for df in [new_york_df, queens_df, bronx_df, kings_df , Richmond_df]:
    df['Id2'] = df['Id2'].astype('int')

In [254]:
# Generate average household size for each dataframe, i.e adding a column in the dataframe:
# for dataframe in dataframe_list:
#     dataframe['avg_hh'] = dataframe['total hh num']/dataframe['total hhsize']
new_york_df['avg_hh'] = new_york_df['total hh num']/ new_york_df['total hhsize']
bronx_df['avg_hh'] = bronx_df['total hh num']/ bronx_df['total hhsize']
queens_df['avg_hh'] = queens_df['total hh num']/ queens_df['total hhsize']
kings_df['avg_hh'] = kings_df['total hh num']/kings_df['total hhsize']
Richmond_df['avg_hh'] = Richmond_df['total hh num']/ Richmond_df['total hhsize']

In [255]:
# Further clean the data by eliminating rows containing NaN:
new_york_df = new_york_df[~np.isnan(new_york_df).any(axis=1)]
bronx_df = bronx_df[~np.isnan(bronx_df).any(axis=1)]
queens_df = queens_df[~np.isnan(queens_df).any(axis=1)]
kings_df = kings_df[~np.isnan(kings_df).any(axis=1)]
Richmond_df = Richmond_df[~np.isnan(Richmond_df).any(axis=1)]

In [256]:
# Calculate the percentage for each household for each dataframe
for df in [new_york_df, queens_df, bronx_df, kings_df , Richmond_df]:
    for i in range(1,7):
        df['percentage_' + str(i)] = df[str(i)]/df['total hhsize']

In [267]:
# Read in the TAZ data:
TAZ = pd.read_csv('TAZ_Household_size-1.csv')
new_york_TAZ = TAZ.loc[0:317].reset_index(drop=True)
queens_TAZ = TAZ.loc[318:751]
bronx_TAZ = TAZ.loc[752:1024]
kings_TAZ = TAZ.loc[1025:1537]
Richmond_TAZ = TAZ.loc[1538:1621]

In [270]:
# The following function aims to match TAZ with corresponding block:
def matching(block_df, TAZ_input):
    # Construct a dict to store all the ID of the residential block and its average hh value:
    block_dict = {}
    for block_row in block_df.itertuples(index=True, name='Pandas'):
        block_dict[getattr(block_row, "avg_hh")] =  getattr(block_row, "Id2")  
    matches = {}
    # Initialize a empty dataframe which to be added to new_york_TAZ:
    columns = ['1','2','3','4','5', '6', '7','avg_hh']
    rows = []
    
    # Iterate through the TAZ table:
    
    for taz_row in TAZ_input.itertuples(index = True, name = 'Pandas'):

        current_hh_target = getattr(taz_row, 'HHSIZE')

        current_taz_id = getattr(taz_row, 'TAZ')

        # Find the closest element in the list according to the target number
        closest_key = min(block_dict.keys(), key=lambda x:abs(x-current_hh_target))
        

        # Retrieve the value stored corresponding to the key, which is the block id:
        current_block_id = block_dict[closest_key]

        matches[current_taz_id] = current_block_id

        row = block_df[block_df['Id2'] == current_block_id][columns].values.tolist()
        row = row[0]
        rows.append(row)
        # Remove the items from block_dict since we could not use the same block_id again:
        block_dict.pop(closest_key)
    
    # Construct a new dataframe to include all these rows:
    to_be_added = pd.DataFrame(rows, columns = columns)
    result = pd.concat([TAZ_input, to_be_added],axis = 1)
    
    return result

In [271]:
result_ny = matching(new_york_df, new_york_TAZ)
result_queens = matching(queens_df, queens_TAZ)
result_bronx = matching(bronx_df, bronx_TAZ)
result_kings = matching(kings_df, kings_TAZ)
result_Richmond = matching(Richmond_df, Richmond_TAZ)
result_Richmond

,TAZ,HHNUM,HHSIZE,1,2,3,4,5,6,7,avg_hh
0,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
1,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
2,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
3,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
4,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
5,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
6,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
7,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
8,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
9,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
10,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
11,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
12,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
13,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
14,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
15,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
16,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
17,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
18,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
19,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
20,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
21,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
22,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
23,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
24,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
25,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
26,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
27,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
28,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
29,NaN,NaN,NaN,225.0,105.0,43.0,25.0,35.0,9.0,4.0,2.042601
...,...,...,...,...,...,...,...,...,...,...,...
1592,1593.0,1722.0,2.768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1593,1594.0,4320.6,2.896,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1594,1595.0,2880.0,2.188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1595,1596.0,918.4,2.798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1596,1597.0,574.0,2.668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1597,1598.0,2799.6,2.928,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1598,1599.0,4395.8,2.818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1599,1600.0,1539.8,2.816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1600,1601.0,3656.2,2.578,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1601,1602.0,0.0,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1602,1603.0,2673.6,2.478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1603,1604.0,1455.2,2.658,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1604,1605.0,2151.0,2.618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1605,1606.0,2428.6,2.788,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1606,1607.0,3795.2,2.806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1607,1608.0,3993.6,2.668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1608,1609.0,2463.0,2.658,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1609,1610.0,1194.2,2.886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1610,1611.0,1720.2,2.928,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1611,1612.0,5617.0,2.726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1612,1613.0,5121.2,2.698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1613,1614.0,4382.6,2.918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1614,1615.0,4684.6,2.856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1615,1616.0,3248.0,2.866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1616,1617.0,4247.2,2.876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1617,1618.0,1685.2,2.908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1618,1619.0,3681.2,2.866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1619,1620.0,2177.0,2.926,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1620,1621.0,2738.8,2.896,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1621,1622.0,1653.8,2.678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [260]:
writer = pd.ExcelWriter('output.xlsx')
result_ny.to_excel(writer,'Sheet1')
result_queens.to_excel(writer,'Sheet2')
result_bronx.to_excel(writer,'Sheet3')
result_kings.to_excel(writer,'Sheet4')
result_Richmond.to_excel(writer,'Sheet5')